import Link from "next/link";
import { notFound } from "next/navigation";
import { Download, Share2, Star } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { samplePacks } from "@/lib/mock-data";

type SharePageProps = {
  params: Promise<{
    pullId: string;
  }>;
};

export default async function SharePage({ params }: SharePageProps) {
  const { pullId } = await params;
  const slug = pullId.toLowerCase();
  const pull = samplePacks
    .flatMap((pack) => pack.pulls)
    .find((item) => item.id.toLowerCase().includes(slug) || item.cardName.toLowerCase().replaceAll(" ", "-") === slug);

  if (!pull) {
    notFound();
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <h1 className="text-3xl font-semibold">Share Pull</h1>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            <span>{pull.cardName}</span>
            <Badge variant="gold">
              <Star className="mr-1 h-3.5 w-3.5" />
              Luck 99.4%
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="rounded-2xl border border-white/10 bg-[linear-gradient(135deg,rgba(123,97,255,0.25),rgba(0,194,255,0.25),rgba(255,207,87,0.2))] p-6">
            <p className="text-sm text-white/75">Pulled {pull.cardName}</p>
            <p className="mt-1 text-2xl font-bold">{pull.rarity}</p>
            <p className="mt-4 text-sm text-white/70">Pack #{pull.packId.replace("pack_", "")} · {pull.setName}</p>
            <p className="text-sm text-white/70">Market value: ${pull.marketValue.toFixed(2)}</p>
            <p className="mt-3 text-xs text-white/60">Generated by RipSense AI Pull Analytics</p>
          </div>
          <div className="mt-4 flex gap-2">
            <Button asChild className="flex-1">
              <Link href={`/api/share/${pullId}`}>
                <Download className="mr-2 h-4 w-4" />
                Download Image
              </Link>
            </Button>
            <Button variant="secondary" className="flex-1">
              <Share2 className="mr-2 h-4 w-4" />
              Copy Share Link
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
