import { ImageResponse } from "next/og";
import { NextResponse } from "next/server";

import { samplePacks } from "@/lib/mock-data";

export const runtime = "edge";

type RouteProps = {
  params: Promise<{
    pullId: string;
  }>;
};

export async function GET(_: Request, { params }: RouteProps) {
  const { pullId } = await params;
  const pull = samplePacks
    .flatMap((pack) => pack.pulls)
    .find((item) => item.id.toLowerCase().includes(pullId.toLowerCase()));

  if (!pull) {
    return NextResponse.json({ error: "Pull not found" }, { status: 404 });
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "48px",
          background:
            "radial-gradient(circle at 20% 10%, rgba(123,97,255,0.65), transparent 45%), radial-gradient(circle at 80% 80%, rgba(0,194,255,0.52), transparent 40%), #0d0c18",
          color: "white",
          fontFamily: "sans-serif",
        }}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ fontSize: 34, fontWeight: 700 }}>RipSense</div>
          <div
            style={{
              border: "1px solid rgba(255,255,255,0.2)",
              borderRadius: 999,
              padding: "6px 16px",
              fontSize: 18,
              color: "#ffcf57",
            }}
          >
            Luck 99.4%
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          <div style={{ fontSize: 52, fontWeight: 800 }}>{pull.cardName}</div>
          <div style={{ fontSize: 28, opacity: 0.85 }}>{pull.rarity}</div>
          <div style={{ fontSize: 22, opacity: 0.8 }}>
            Pack #{pull.packId.replace("pack_", "")} · {pull.setName}
          </div>
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ fontSize: 24, color: "#ffcf57" }}>${pull.marketValue.toFixed(2)}</div>
          <div style={{ fontSize: 20, opacity: 0.7 }}>Generated by RipSense AI Pull Analytics</div>
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
    },
  );
}
